version: "3.8"

services:
        nginx-site:
                build:
                        context: .
                        dockerfile: Dockerfile
                restart: always
                container_name: findcourier-site
                network_mode: host
                volumes:
                        - /var/lib/findcourier:/var/lib/findcourier
